### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by orsinium** [appsignal/appsignal-python#87]
1. CI seems to not run for my PRs.
2. CI seems to fail in the `main` branch.
3. CI output is not available for non-maintainers. When I press on Github "Details", it sends me to a workflows page that simply shows 404.

If I may suggest, GitHub Actions is a good choice for Github-based open-source projects. I don't like the way how GitHub Actions are configured, but they have the best integration with GitHub and none of the issues listed above.

**Comment by unflxw** [comment]
Thanks for bringing this to our attention!

> 1. CI seems to not run for my PRs.

I noticed that, yes. I'll look into it -- there must be something wrong with how Semaphore is configured in this repository, since CI runs fine for PRs made from forks of our other repositories. Here's [an example](https://github.com/appsignal/appsignal-ruby/pull/967), in our Ruby integration repository.

> 2. CI seems to fail in the `main` branch.

The check that's failing is [Lintje](https://lintje.dev), our Git commit linter, which checks that commits have descriptions (not just commit messages) and the formatting of those descriptions. It took issue with one of your commit descriptions not being [line-wrapped to 72 characters](https://lintje.dev/docs/rules/commit-message/#messagelinelength). Don't worry about it much -- the tests and code formatting and such are all passing. Lintje only checks the most recent push, so it will be green for the next merge.

> 3. CI output is not available for non-maintainers. When I press on Github "Details", it sends me to a workflows page that simply shows 404.

Unfortunately, as far as I'm aware, this is a limitation of our Semaphore setup. I'll see if there's a way around it while I'm looking for the right box to tick on Semaphore's configuration.

> If I may suggest, GitHub Actions is a good choice for Github-based open-source projects.

Nothing against GitHub Actions personally, but we use Semaphore for CI in most of our projects. While I would like us to have a system that is friendlier for maintainers, but I don't think we'll invest our efforts into changing this in the short term.

**Comment by orsinium** [comment]
Thanks, I'll make sure to wrap the commit messages. I never bothered with that before because I've never encountered an interface that would display commit messages but wouldn't know how to nicely wrap them.

**Comment by tombruijn** [comment]
> CI output is not available for non-maintainers. When I press on Github "Details", it sends me to a workflows page that simply shows 404.

I've made the CI project public (like our other open source projects). It should be viewable now on https://appsignal.semaphoreci.com/projects/appsignal-python and direct links.

**Comment by tombruijn** [comment]
> CI seems to not run for my PRs.

I found that the option to run builds for PRs from forks was not enabled. It is now! Your PRs should now be build by Semaphore :)

**Comment by tombruijn** [comment]
Closing this issue as most things seem resolved.

About switching to GitHub. I wouldn't say it's something we won't do, but we use Semaphore for most of our projects and I don't think the GitHub setup will work for all our projects.
My main reason for switching away is not having to wait for Semaphore to update their tooling to support newer versions of languages we want to test against.
